In [1]:
from nbapy import draft_combine
import pandas as pd

# stats

In [2]:
pd.DataFrame(draft_combine.DrillResults().stats())

,TEMP_PLAYER_ID,PLAYER_ID,FIRST_NAME,LAST_NAME,PLAYER_NAME,POSITION,STANDING_VERTICAL_LEAP,MAX_VERTICAL_LEAP,LANE_AGILITY_TIME,MODIFIED_LANE_AGILITY_TIME,THREE_QUARTER_SPRINT,BENCH_PRESS
0,1629638,1629638,Nickeil,Alexander-Walker,Nickeil Alexander-Walker,SG,NaN,NaN,NaN,NaN,NaN,NaN
1,1629628,1629628,RJ,Barrett,RJ Barrett,SF,NaN,NaN,NaN,NaN,NaN,NaN
2,1629646,1629646,Charles,Bassey,Charles Bassey,C,29.0,33.0,12.65,3.27,3.53,7.0
3,1629647,1629647,Darius,Bazley,Darius Bazley,PF,30.5,37.0,11.09,2.95,3.27,4.0
4,1629626,1629626,Bol,Bol,Bol Bol,C,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
72,1629632,1629632,Coby,White,Coby White,PG,NaN,NaN,NaN,NaN,NaN,NaN
73,1629025,1629025,Kris,Wilkes,Kris Wilkes,SF,27.5,35.0,10.39,3.09,3.34,4.0
74,1629684,1629684,Grant,Williams,Grant Williams,PF,26.0,31.5,10.83,3.27,3.33,20.0
75,1629627,1629627,Zion,Williamson,Zion Williamson,PF,NaN,NaN,NaN,NaN,NaN,NaN
76,1629685,1629685,Dylan,Windler,Dylan Windler,SF,29.0,37.5,10.70,2.94,3.30,8.0